= Multi-Agent Oriented Programming
Programming Multi-Agent Systems Using JaCaMo
:toc: right

Olivier Boissier, Rafael H. Bordini, Jomi Fred Hübner and Alessandro Ricci +
MIT Press, September 2020


This page contains additional information and material for the book link:https://mitpress.mit.edu/books/multi-agent-oriented-programming[Multi-Agent Oriented Programming].

== Examples and Exercises

All the code used in the book (examples and exercises) is available for download link:./maop-code.zip[here].
The examples are organised in directories with the same structure as the book.
For instance, the example _Single Agent Hello World_ (chapter 3, section 3.1) is placed in the directory `sec3.1`.

To run the examples you need to install

- Java >= 17 (ensure that the environment variable `JAVA_HOME` is properly set)

and then simply execute the `gradlew` (or `gradlew.bat`) program that is available in the directory:
-----
cd sec3.1
./gradlew
-----

Example of output:
----
[bob] Hello World
----

NOTE: to edit the code, create new projects and discover other options to run the application, see the link:https://jacamo-lang.github.io/[JaCaMo web site].

NOTE: the JaCaMo version used in the book is 1.1

// == Slides

// coming soon...

// == Some links

// - In the http://jacamo.sf.net[JaCaMo web site] you can find more examples and documentation.
