# Writing JaCaMo documentation
:toc: right
:author: JaCaMo Team
:date: March 2023
:source-highlighter: coderay
:coderay-linenums-mode: inline
:icons: font
:prewrap!:

ifdef::env-github[:outfilesuffix: .adoc]

This document presents some guidelines for writing documentation for JaCaMo.

The preferred documentation tool is https://asciidoc.org[AsciiDoc]. Of course, in some circumstances other formats are more suited. When someone commit and push `.adoc` files into  the JaCaMo-doc repository, they are automatically translated into  HTML and placed  in the https://jacamo-lang.github.io/documentation/[JaCaMo web site].

== Files and Folders

* Every document has its own folder. 
* `index.adoc` is the entry point.
* if the documentation is accompanied with programs, they should be placed under a directory named `code`.
* figures should be placed into a `figs` folder.

For example, it follows the organization of files of the getting started documentation:
----
getting-started
├── index.adoc
├── code
│   └── my1st-app
│       ├── my1st_app.jcm
│       └── src
└── figs
    ├── screen-env1.png
    ├── screen-mind1.png
    ├── screen-mind2.png
    ├── screen-mind3.png
    ├── screen-org1.png
    └── screen-vsc1.png
----

== AsciiDoc details

=== Preamble

The proposed preamble of AsciiDoc documents is:

----
# The title of the documentation
:toc: right
:author: JaCaMo Team
:date: March 2023
:source-highlighter: coderay
:coderay-linenums-mode: inline
:icons: font
:prewrap!:

ifdef::env-github[:outfilesuffix: .adoc]
----

=== Links 

Links to other documents available in JaCaMo doc repository should be written  as relative links without the explicit file extension (because inside GitHub `.adoc` is used, but the web site uses `.html` instead).

Example:
----
It is detailed in link:../getting-started/index{outfilesuffix}[Getting Started]
----

that produces:
====
It is detailed in link:../getting-started/index{outfilesuffix}[Getting Started]
====

=== Programs

Programs should be formatted following the link:../programming-style/index{outfilesuffix}[JaCaMo programming style for source code]. Source code should be included into the AsciiDoc files as follows:

[source,asciidoc]
....
[source,jacamoproject,linenums]
.my1st_app.jcm
----
mas my1st_app {

    agent alice
    agent bob

}
----
....

and
[source,asciidoc]
....
[source,jasonagent,linenums]
.alice.asl
----
!say_hello.   // initial goal

+!say_hello   // plan to achieve goal say_hello
   <- .send(bob,tell,greeting("hello world")).

// some usual includes for JaCaMo projects:
{ include("$jacamoJar/templates/common-cartago.asl") }
{ include("$jacamoJar/templates/common-moise.asl") }
{ include("$moiseJar/asl/org-obedient.asl") }
----
....

NOTE: https://docs.asciidoctor.org/asciidoc/latest/directives/include/[Including files] from `code` directory is not suggested for now! It works on the the produced HTML, but unfortunately do not work when reading the documentation directly on GitHub.

NOTE: some guidelines should to be revised when syntax highlight is implemented.


=== More on AsciiDoc

is found at https://docs.asciidoctor.org/asciidoc/latest[here].