# Writing JaCaMo documentation
:toc: right
:author: JaCaMo Team
:date: March 2023
:source-highlighter: coderay
:coderay-linenums-mode: inline
:icons: font
:prewrap!:


This document presents some guidelines for writing documentation for JaCaMo.

The preferred documentation tool is https://asciidoc.org[AsciiDoc]. Of course, in some circumstances other formats are more suited. When someone commit and push `.adoc` files into  the JaCaMo-doc repository, they are automatically translated into  HTML and placed  in the https://jacamo-lang.github.io/documentation/[JaCaMo web site].

== Global Considerations

* The documentation repository consolidates all the docs of all JaCaMo repositories that are not directly written alongside the code (in the actual program code files). 
* The documentation repository contains the JaCaMo project overview page. 
* The documentations are all deployed to the same domain.
* The Java Doc/API documentation should be hosted there as well. 
//* Ideally, workflows (GitHub Actions) will be configured to automatically update the deployed docs when the source (either ‘non-code’ docs or Java doc) has been changed.
* Avoid the use of stale technologies in the doc

//** Move from Atom to VSCode
//** Consider moving from Eclipse to IntelliJ

== Files and Folders

* Every document has its own folder. 
* `readme.adoc` is the entry point.
* if the documentation is accompanied with programs, they should be placed under a directory named `code`.
* figures should be placed into a `figs` folder.

For example, it follows the organization of files of the getting started documentation:
----
getting-started
├── readme.adoc
├── code
│   └── my1st-app
│       ├── my1st_app.jcm
│       └── src
└── figs
    ├── screen-env1.png
    ├── screen-mind1.png
    ├── screen-mind2.png
    ├── screen-mind3.png
    ├── screen-org1.png
    └── screen-vsc1.png
----

You can start your document by copying the structure from the template:

----
cp -r template your-doc-name
----

This template has `code` and `figs` directories, so remove them if their are not necessary.

== Proposed TOC

The proposed sections are:

- What You Will Build
- What You Need
- Initial code
- other sections
- What you have learnt

Of course, different documents may have other structure. 

== AsciiDoc details

=== Preamble

The proposed preamble of AsciiDoc documents is:

----
# The title of the documentation
:toc: right
:author: JaCaMo Team
:date: March 2023
:source-highlighter: coderay
:coderay-linenums-mode: inline
:icons: font
:prewrap!:
----

=== Links 

Links to other documents available in JaCaMo doc repository should be written  as relative links using `xref`. With `xref` `.adoc` is properly replaced by `.html` when necessary.

Example:
----
It is detailed in xref:../getting-started/readme.adoc[Getting Started]
----

that produces:
====
It is detailed in xref:../getting-started/readme.adoc[Getting Started]
====

=== Programs

Programs should be formatted following the xref:../programming-style/readme.adoc[JaCaMo programming style for source code]. Source code should be included into the AsciiDoc files as follows:

[source,asciidoc]
....
[source,jacamoproject,linenums]
.my1st_app.jcm
----
mas my1st_app {

    agent alice
    agent bob

}
----
....

and
[source,asciidoc]
....
[source,jasonagent,linenums]
.alice.asl
----
!say_hello.   // initial goal

+!say_hello   // plan to achieve goal say_hello
   <- .send(bob,tell,greeting("hello world")).

// some usual includes for JaCaMo projects:
{ include("$jacamoJar/templates/common-cartago.asl") }
{ include("$jacamoJar/templates/common-moise.asl") }
{ include("$moiseJar/asl/org-obedient.asl") }
----
....

NOTE: https://docs.asciidoctor.org/asciidoc/latest/directives/include/[Including files] from `code` directory is not suggested for now! It works on the the produced HTML, but unfortunately do not work when reading the documentation directly on GitHub.

NOTE: some guidelines should to be revised when syntax highlight is implemented.


=== More on AsciiDoc

is found at https://docs.asciidoctor.org/asciidoc/latest[here].
