= JaCaMo contributing guide
:toc: right
:author: JaCaMo Team
:date: March 2023
:source-highlighter: coderay
:coderay-linenums-mode: inline
:icons: font
:prewrap!:

This document serves as the guide for contributing to JaCaMo project.

== Publishing your questions

Making your questions public can help other users. You can use https://stackoverflow.com/[stack overflow] for it, or reporting an issue on GitHub (next topic).

== Reporting an issue

Issues can be reported on GitHub issues (e.g.: https://github.com/jacamo-lang/jacamo/issues[issues for JaCaMo main project].

== Making a Pull-Request

Pull-Requests are welcome.

== Being part of the team

Please, let the team know if you want to come on board.

=== Git Branches and Workflow

master or main:: Latest stable version and bug fixes.
develop:: Branch for developing new features.
other branchs:: Other branches can be created for large features and hotfixes.

=== JaCaMo Repository Structure

JaCaMo related projects are stored on https://github.com/orgs/jacamo-lang[jacamo-lang github organization].

jacamo:: The main project that parses JCM files and joins, among other modules, Jason, CArtAgO and Moise.
documentation:: A repository to centralize the documentation of the JaCaMo project such as manuals and tutorials.
mvn-repo:: A repository for storing JaCaMo maven packages. It is needed to add on the `build.gradle` of the application the repository `maven { url "https://raw.githubusercontent.com/jacamo-lang/mvn-repo/master" }`.
eclipse-jacamo-plugin:: The JaCaMo plugin for eclipse.

=== Project Roadmap

The project roadmap is organized on GitHub issues and project notes listed on https://github.com/orgs/jacamo-lang/projects/1[JaCaMo NEXT Project Board].

==== Development Iteration
The iteration cycle follows the usual team meeting schedule, which occurs every 2 weeks.

==== Issue Status
No Status:: An issue that is not prioritize for the current iteration.
Under Discussion:: An issue under assynchronous discussion or waiting for synchronous discussion.
Backlog:: An issue to be developed in the current iteration. Usually, a developer is assigned to it.
In Progress:: An issue under development.
In Review:: An issue waiting for revision. Usually, a reviewer is assigned to it.
Done:: The issue is solved. The issue can be removed from the board when a new iteration starts.